apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot-nginx
  template:
    metadata:
      labels:
        app: telegram-bot-nginx
    spec:
      containers:
        - name: telegram-bot-nginx
          image: nginx
          ports:
            - containerPort: 80
          env:
            - name: NGINX_HOST
              value: localhost
            - name: NGINX_PORT
              value: "80"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config