version: '3.8'

services:
  telegram-bot:
    image: telegram-bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    extends:
      file: ../src/docker-compose.override.yml
      service: telegram.bot.webapi
  telegram.bot.db:
    extends:
      file: ../src/docker-compose.override.yml
      service: telegram.bot.db
      
networks:
  telegram-bot:

volumes:
  postgres-data:
  shared-images:
