version: '3.4'

services:

  telegram.bot.webmvc:
    image: ${DOCKER_REGISTRY}telegrambotwebmvc
    build:
      context: .
      dockerfile: Telegram.BOT.WebMVC/Dockerfile

  telegram.bot.telegramjob:
    image: ${DOCKER_REGISTRY}telegrambottelegramjob
    build:
      context: .
      dockerfile: Telegram.BOT.TelegramJob/Dockerfile

  telegram.bot.db:
    image: postgres:latest
    restart: always

  telegram.bot.services:
    image: ${DOCKER_REGISTRY-}telegrambotservices
    build:
      context: .
      dockerfile: Telegram.BOT.Services/Dockerfile

networks:
  telegram-bot:



