version: '3.4'
name: telegrambot
services:

  telegram.bot.telegramjob:
    image: gabriel159487/telegrambottelegramjob:latest
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
        reservations:
          cpus: '0.20'
          memory: 200M
    env_file:
      - env/common.env
      - env/databases.env
    restart: always
    networks:
      - telegram-bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - static-files:/app/wwwroot/
    depends_on:
      - telegram.bot.db

  telegram.bot.db:
    image: postgres:latest
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
        reservations:
          cpus: '0.20'
          memory: 200M
    restart: always
    ports:
      - 5548:5432
    networks:
      - telegram-bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  telegram.bot.services:
    image: gabriel159487/telegrambotservices:latest
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
        reservations:
          cpus: '0.20'
          memory: 200M
    env_file:
      - env/common.env
      - env/databases.env
    networks:
      - telegram-bot
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - static-files:/app/wwwroot/
    depends_on:
      - telegram.bot.db

  telegram.bot.webmvc:
    image: gabriel159487/telegrambotwebmvc:latest
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
        reservations:
          cpus: '0.20'
          memory: 200M
    build:
      context: .
      dockerfile: Telegram.BOT.WebMVC/Dockerfile
    env_file:
      - env/common.env
      - env/databases.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "62235:443"
      - "62236:80"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - static-files:/app/wwwroot/
    networks:
      - telegram-bot
    depends_on:
      - telegram.bot.db

networks:
  telegram-bot:

volumes:
  postgres-data:
  static-files:
