version: '3.4'
name: telegrambot
services:

  telegram.bot.telegramjob:
    image: gabriel159487/telegrambottelegramjob:latest
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 100M
    env_file:
      - env/common.env
      - env/databases.env
    restart: always
    networks:
      - telegram-bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - static-files:/app/wwwroot/

  telegram.bot.services:
    image: gabriel159487/telegrambotservices:latest
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 100M
    env_file:
      - env/common.env
      - env/databases.env
    networks:
      - telegram-bot
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - static-files:/app/wwwroot/

  telegram.bot.webmvc:
    image: gabriel159487/telegrambotwebmvc:latest
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 200M
        reservations:
          cpus: '0.10'
          memory: 100M
    env_file:
      - env/common.env
      - env/databases.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - URL_PREFIX=/mandabot
    ports:
      - "62236:80"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - static-files:/app/wwwroot/
    networks:
      - telegram-bot

networks:
  telegram-bot:
    external: true
    name: system_services_system_services


volumes:
  postgres-data:
    external: true
    name: system_services_postgres-data
  static-files:
    external: true
    name: system_services_static-files


