version: '3.4'

services:

  telegram.bot.telegramjob:
    image: ${DOCKER_REGISTRY}telegrambottelegramjob
    build:
      context: .
      dockerfile: Telegram.BOT.TelegramJob/Dockerfile
    env_file:
      - env/common.env
      - env/databases.env
    networks:
      - telegram-bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - static-files:/app/wwwroot/
    depends_on:
      - telegram.bot.db

  telegram.bot.db:
    image: postgres:latest
    restart: always
    ports:
      - 5548:5432
    networks:
      - telegram-bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  telegram.bot.services:
    image: ${DOCKER_REGISTRY-}telegrambotservices
    build:
      context: .
      dockerfile: Telegram.BOT.Services/Dockerfile
    env_file:
      - env/common.env
      - env/databases.env
    networks:
      - telegram-bot
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - static-files:/app/wwwroot/
    depends_on:
      - telegram.bot.db

  telegram.bot.webmvc:
    image: ${DOCKER_REGISTRY}telegrambotwebmvc
    build:
      context: .
      dockerfile: Telegram.BOT.WebMVC/Dockerfile
    env_file:
      - env/common.env
      - env/databases.env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "62236:80"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - static-files:/app/wwwroot/
    networks:
      - telegram-bot
    depends_on:
      - telegram.bot.db

networks:
  telegram-bot:

volumes:
  postgres-data:
  static-files: