name: Build and Push Docker Images
on:
  push:
    branches:
      - master  # Adjust as needed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_SERVER_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Compose Services
        env:
          DOCKER_BUILDKIT: 1
        run: |
          echo "Logging into Azure Container Registry..."
          echo "Server: ${{ secrets.ACR_SERVER_NAME }}"
          echo "Username: ${{ secrets.ACR_USERNAME }}"
          echo "Password: ********"
          
          cd src/
          echo "Current directory: $(pwd)"
          
          echo "Building Docker Compose services..."
          docker-compose -f docker-compose.override.yml build
          
          echo "List of images built:"
          docker images
          
          echo "Pushing Docker Compose services..."
          docker-compose -f docker-compose.override.yml push
          
          echo "List of images pushed:"
          docker images
